# Generated by Django 4.1 on 2022-08-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtd_stop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtd_route_id', models.IntegerField()),
                ('rtd_route_long_name', models.CharField(max_length=255)),
                ('rtd_stop_sequence', models.IntegerField()),
                ('direction', models.CharField(max_length=25)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stop', to='backend.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('has_bench', models.BooleanField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Route', to='backend.route')),
            ],
        ),
    ]
