# Generated by Django 4.1 on 2022-08-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rtd_route_id',
            field=models.CharField(max_length=25),
        ),
    ]
