# Generated by Django 4.1 on 2022-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='user_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
