# Generated by Django 4.1 on 2022-08-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_route_rtd_route_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='route',
        ),
        migrations.AddField(
            model_name='recording',
            name='stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recording_stop', to='backend.stop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stop', to='backend.stop'),
        ),
    ]
